### ISSUE TITLE
Ineligible for ontology conversion

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-issue-repo#17]
- [ ]     opentargets
- [ ]     gwas
- [ ]     clinvar
- [ ]     markerdb (which also needs term name fixing, as indicated previously) https://github.com/clinical-biomarkers/OBCI/issues/20
- [ ] PMC (LINCS)
- [ ] CIViC (issues in data) https://github.com/clinical-biomarkers/OBCI/issues/21
- [ ] oncomx (issues in data) https://github.com/clinical-biomarkers/OBCI/issues/22
dbSNP not handled in ontology
ontology not prepped for panels
